# デフォルトのapplication.yaml
# アプリケーションで指定したapplication.yamlとマージされます。
# 同名のキーをアプリケーションで指定した場合は、アプリケーションのキーで上書きされます。

# SpringBootとしてのログレベルを開発用に設定します
# 詳細：https://docs.spring.io/spring-boot/reference/features/logging.html
# 開発モードを有効にする
debug: true

logging:
  pattern:
    # correlationの出力パターンのカスタマイズ（traceId-spanIdから変更）
    # https://docs.spring.io/spring-boot/reference/actuator/tracing.html#actuator.micrometer-tracing.logging
    correlation: "[%32X{traceId}]"
  # ログレベルの設定
  level:
    root: INFO # 基本となるログレベルの設定
    org.springframework.boot.autoconfigure.logging.ConditionEvaluationReportLogger: INFO # debug=trueで出力されるAutoConfigurationレポートは流石に量が多すぎるため抑制する

server:
  servlet:
    session:
      tracking-modes:
        - cookie

# /actuator/shutdownの有効化
management:
  endpoint.shutdown.access: unrestricted
  endpoints.web.exposure.include: health, shutdown

spring:
  mvc:
    log-request-details: true # DispatcherServletが出力するリクエストログの情報量を増やす
